### ISSUE TITLE
Get an error when get price in specified block number

### ISSUE THREAD

**Issue by zjymoty** [1inch/spot-price-aggregator#108]
```python
        block = 17806056
        rate = self.oracle.functions.getRateToEthWithThreshold(
            token_address, True, 20
        ).call(block_identifier=block)
        numerator, denominator = (
            10 ** Token(self.chain, token_address, self.w3).decimals,
            1e18,
        )
```

When I use 1 inch spot price aggregator to get price on a block 150 days ago, I got this error `web3.exceptions.BadFunctionCallOutput: Could not decode contract function call to getRateToEthWithThreshold with return data: b'', output_types: ['uint256']`

How can I solve it?

**Comment by zZoMROT** [comment]
It seems you're using the latest version of OffchainOracle (`0x0AdDd25a91563696D8567Df78D5A01C9a991F9B8`, or `0xc9bB6e4FF7dEEa48e045CEd9C0ce016c7CFbD500` on zksync). Please be aware that the contract you're attempting to interact with hasn't been deployed yet in the block you're referencing. Specifically, the contract was deployed in block `18040583`, but you're trying to call a method on it in block `17806056`.

To address this issue, especially if you need the price data from a block prior to the contract's deployment, you have a couple of options:
- use an older version of OffchainOracle that was already deployed at the block of your interest (you can find the older versions in the README for each network)
- fork the network at the block you're interested in, then deploy the code of the current OffchainOracle in this forked version of the network, and use it there

**Comment by zjymoty** [comment]
Thank you very much!
I learned a lot of you and I will try your suggestions.
