### ISSUE TITLE
Issue with Uniswap V3 Gas Limit Estimation

### ISSUE THREAD

**Issue by EthanScully** [1inch/spot-price-aggregator#11]
I've checked a few times and the current deployed build is over estimating the gas limit of Uniswap V3 single swap transactions by 30%. I've checked swapping 0.01 Eth to DAI. I'm not sure if this exists on other Dex's estimations but it should be looked into. And hopefully I'm in the right place.

**Comment by shoom3301** [comment]
Hello Ethan!
Thanks for your question.
In 1inch Dapp we add some overhead to `gasLimit` to avoid **Out of Gas** errors, because a route could be complicated.
