### ISSUE TITLE
missing price

### ISSUE THREAD

**Issue by jpsains** [1inch/spot-price-aggregator#118]
Hey,

Love the project. Im looking for some advice.

This token 0xFe459828c90c0BA4bC8b42F5C5D44F316700B430 is returning 0 

https://etherscan.io/address/0xfe459828c90c0ba4bc8b42f5c5d44f316700b430

Is there a way to get a price for it?

I tried to get a price vs a few different tokens but seems its zero still
<img width="582" alt="image" src="https://github.com/1inch/spot-price-aggregator/assets/32621022/f6ebf763-02c8-45e7-b9c6-84bea5dcda59">

**Comment by zZoMROT** [comment]
Thank you for your interest in the project and for reaching out with your question.

Regarding the token `0xFe459828c90c0BA4bC8b42F5C5D44F316700B430` not showing a price, you're correct in your observation. Currently, the liquidity for this token appears to be present only on `Bancor`, specifically in a pool with the `BNT` token.

There are a couple of reasons you're encountering this issue:
- The `SpotPriceAggregator` does not support Bancor. This means that any liquidity or pricing data from Bancor is not currently being considered in price calculations.
- Even if we were to integrate a BancorOracle for `SpotPriceAggregator`, the token in question does not have a pairing with WETH or any of the other connector tokens. This absence of a direct pairing means that the pool would not be included in the pricing model for the token.

As a potential solution, it could be creating (you can try to ask token owner about it, for example) a liquidity pool on a DEX that is supported by `SpotPriceAggregator`, in a pairing that includes your token. It's important to ensure that the pool is provided with sufficient liquidity to allow for effective arbitrage. This would enable traders to engage in transactions that help maintain an accurate price for the token.

By establishing a pool in a supported DEX, it's not only facilitate a more reliable valuation of token but also potentially increase its visibility and accessibility to a wider audience of traders and investors.

We appreciate your understanding and are here to help with any further questions.
