### ISSUE TITLE
AVAX USDT -> USDC returning wrong rate

### ISSUE THREAD

**Issue by blakearnold** [1inch/spot-price-aggregator#146]
0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7 (USDT) -> 0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e (USDC)

It's returning a rate of 9934357914 / 10^18. It almost looks like there is a precision issue here but since both USDT and USDC are 6 precision the rate should be 18 decimal places.

<img width="513" alt="Screenshot 2024-05-21 at 7 33 06 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/a7614360-2a61-49aa-9ce0-f81be447413f">

Some counter example that do work:
0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7 (USDT) -> 0xc7198437980c041c805a1edcba50c1ce5db95118 (USDT.e)
<img width="503" alt="Screenshot 2024-05-21 at 7 35 01 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/a626666f-5a89-4e1b-9076-830ffee894c5">

0xc7198437980c041c805a1edcba50c1ce5db95118 (USDT.e) -> 0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e (USDC)
<img width="502" alt="Screenshot 2024-05-21 at 7 35 43 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/f3570686-10a1-4150-810b-7e6449aff39e">

**Comment by blakearnold** [comment]
pulled the trace, this looks specific to the curve oracle:
```
    ├─ [850659] CurveOracle::getRate(TransparentUpgradeableProxy: [0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7], FiatTokenProxy: [0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E], 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF, 50) [staticcall]
│   └─ ← [Return] 9934472063 [9.934e9], 117951579944830751724 [1.179e20]
```

0x715C0357F8F29FB7a71acDcaeFdde2B964824B23
<img width="488" alt="Screenshot 2024-05-22 at 10 19 11 AM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/88e8a10f-f146-4dd3-bb64-897e037353d6">


Other oracles give the correct rate

https://snowscan.xyz/address/0xc197Ab9d47206dAf739a47AC75D0833fD2b0f87F#readContract
<img width="458" alt="Screenshot 2024-05-22 at 10 22 24 AM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/ad99335d-c131-4638-8219-f5af71038ea2">
```
    ├─ [14133] UniswapV2LikeOracle::getRate(TransparentUpgradeableProxy: [0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7], FiatTokenProxy: [0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E], 0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664, 50) [staticcall]
    │   ├─ [2517] JoePair::getReserves() [staticcall]
    │   │   └─ ← [Return] 6916567 [6.916e6], 6923485 [6.923e6], 1715348913 [1.715e9]
    │   ├─ [2517] JoePair::getReserves() [staticcall]
    │   │   └─ ← [Return] 247655750500 [2.476e11], 247480326898 [2.474e11], 1716375593 [1.716e9]
    │   └─ ← [Return] 1000291040338364393 [1e18], 6920025 [6.92e6]
```

```
    ├─ [14836] UniswapV2LikeOracle::getRate(TransparentUpgradeableProxy: [0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7], FiatTokenProxy: [0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E], 0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664, 50) [staticcall]
    │   ├─ [2893] PangolinPair::getReserves() [staticcall]
    │   │   └─ ← [Return] 144851 [1.448e5], 144414 [1.444e5], 1690870816 [1.69e9]
    │   ├─ [2893] PangolinPair::getReserves() [staticcall]
    │   │   └─ ← [Return] 129876875258 [1.298e11], 129920124713 [1.299e11], 1716385793 [1.716e9]
    │   └─ ← [Return] 997314481777826870 [9.973e17], 144632 [1.446e5]

    ├─ [14146] UniswapV2LikeOracle::getRate(TransparentUpgradeableProxy: [0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7], FiatTokenProxy: [0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E], 0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664, 50) [staticcall]
    │   ├─ [2517] UniswapV2Pair::getReserves() [staticcall]
    │   │   └─ ← [Return] 45521 [4.552e4], 45236 [4.523e4], 1704402457 [1.704e9]
    │   ├─ [2517] UniswapV2Pair::getReserves() [staticcall]
    │   │   └─ ← [Return] 15665699363 [1.566e10], 15672854134 [1.567e10], 1716384258 [1.716e9]
    │   └─ ← [Return] 994178511016893301 [9.941e17], 45378 [4.537e4]

```

**Comment by zZoMROT** [comment]
Thank you for bringing this issue to our attention.

I am in touch and have already localized the problem. It is in the Curve pool `0xd2acae14ae2ee0f6557ac6c6d0e407a92c36214b`.

The registry `0x8474DdbE98F5aA3179B3B3F5942D724aFcdec9f6` (which contains this pool), through the method `get_coin_indices`, indicates that the tokens are underlying (and this is true for this pool). However, the pool's method `get_dy_underlying` returns strange results because Curve does not natively support Aave token wrapping and unwrapping in their newer NG pools.

I have already reached out the Curve team to clarify the nuances of this pool's operation, and I hope we can fix this issue soon in CurveOracle.

**Comment by zZoMROT** [comment]
The Oracle has been updated. The non-standard functioning Curve pool is now ignored. Attached is a screenshot showing the correct results for the issue found.
Thank you for your attention to this matter.
<img width="856" alt="Screenshot" src="https://github.com/1inch/spot-price-aggregator/assets/3616087/f92361d8-5213-4d0d-9f20-30ee103e3f81">

**Comment by zZoMROT** [comment]
Yes, this issue due to a similar few non-standard curve pools on mainnet.
The oracle on the mainnet has already been updated, and the issue has been fixed.
Thank you for the improvement suggestion!

<img width="667" alt="Снимок экрана 2024-06-28 в 11 38 55" src="https://github.com/1inch/spot-price-aggregator/assets/3616087/81c8a219-d49b-4976-b5f0-a4a92db33e81">
