### ISSUE TITLE
[feature] Add Aerodrome Oracle on Base Chain

### ISSUE THREAD

**Issue by blakearnold** [1inch/spot-price-aggregator#147]
Seeing more tokens only listed on Aerodrome on Base, an example is WELL - 0xa88594d404727625a9437c3f886c7643872296ae
No price can be found
https://basescan.org/address/0x0AdDd25a91563696D8567Df78D5A01C9a991F9B8#readContract
<img width="392" alt="Screenshot 2024-05-22 at 7 45 47 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/45c59c5e-70a7-43e7-899c-05f5fda98a60">

8 million of liquidity
<img width="764" alt="Screenshot 2024-05-22 at 7 50 29 PM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/b60ff25d-76bc-406b-a8b5-b81d71c0fdd8">

**Comment by cstoneham** [comment]
Would appreciate this as well 🙏🏻

**Comment by zZoMROT** [comment]
Thank you for improving the Oracle and drawing attention to the missed liquidity.

<img width="663" src="https://github.com/1inch/spot-price-aggregator/assets/3616087/55295731-6940-4a59-8b7b-15c7d368cdd2">
