### ISSUE TITLE
Add USDC connector to BASE

### ISSUE THREAD

**Issue by blakearnold** [1inch/spot-price-aggregator#149]
The oracle cannot get the rate of Base's WGC - 0xfb18511f1590a494360069f3640c27d55c2b5290 against ETH.
Looks like there is only a pool with USDC.

I noticed that USDC is a default connector on most chains except Base and Arbitrum, could you add it on both of those?

<img width="526" alt="Screenshot 2024-05-30 at 11 30 51 AM" src="https://github.com/1inch/spot-price-aggregator/assets/136089/36993c6b-4c7f-40f6-9603-b75179699019">

**Comment by Admin661** [comment]
Hello @blakearnold you will have to rectify with the 1inch loptimal weblink and try it again.

**Comment by zZoMROT** [comment]
Thank you for your suggestion. I will bring this proposal into our discussions and ensure to get back to you with an update on the addition of the connector or with an explanation if we decide not to proceed with it.

**Comment by Admin661** [comment]
Alright

**Comment by zZoMROT** [comment]
We've added `USDC` as a connector on both the `base` and `arbitrum` networks. Now the oracle can get the rate of `base`'s `WGC` token to `ETH` without needing a custom connector.

<img width="664" alt="Screenshot" src="https://github.com/1inch/spot-price-aggregator/assets/3616087/b96e2822-f050-4d70-9fef-19ef2f419e86">

Thanks for your patience!
