### ISSUE TITLE
Use the Native USDC issued by Circle connector on Polygon

### ISSUE THREAD

**Issue by blakearnold** [1inch/spot-price-aggregator#157]
The Polygon USDC connector asset is the old bridged USDC.
https://www.circle.com/blog/native-usdc-now-available-on-polygon-pos

Consider adding the new bridged USDC as a connector:

Bridged USDC from Ethereum
Token Symbol: USDC.e
Token Address: [0x2791bca1f2de4661ed88a30c99a7a9449aa84174](https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174)
 

Native USDC issued by Circle
Token Symbol: USDC
Token Address: [0x3c499c542cef5e3811e1192ce70d8cc03d5c3359](https://polygonscan.com/token/0x3c499c542cef5e3811e1192ce70d8cc03d5c3359)

**Comment by zZoMROT** [comment]
We have already added this connector. Thank you for the improvement suggestion!
