### ISSUE TITLE
Can we add a new function to return price and liquidity at the same time?

### ISSUE THREAD

**Issue by wangereth** [1inch/spot-price-aggregator#166]
It's useful to determine the confidence of the price when liquidity is low.

**Comment by zZoMROT** [comment]
Given that `OffchainOracle` aggregates prices from various liquidity sources, each with different levels of liquidity, it is not clear what average liquidity value should be shown for a weighted average price. You can query the oracles of specific protocols to get the price and corresponding liquidity within that specific protocol.

Would it be useful for you to have a method for obtaining the price where you can specify the minimum liquidity you would like to consider when calculating the weighted average price?

**Comment by wangereth** [comment]
Yes, the "a method for obtaining the price where you can specify the minimum liquidity you would like to consider when calculating the weighted average price" idea is what I want. Thank you!

**Comment by zZoMROT** [comment]
I'm going to expose the internal method that retrieves data from the Oracles and make this method public (accessible for you to call). This method will return an array of objects containing prices and liquidity weights (the data used for calculating the weighted rate), allowing you to filter and use them in any way that suits your needs. I believe this will be useful for you.

**Comment by wangereth** [comment]
Cool! Thanks so much!

**Comment by zZoMROT** [comment]
You can find the method you need in the latest version of the `OffchainOracle`:
- `0x739B4e7a3ad8210B6315F75b24cfe0D3226f6945` on the zkSync network
- `0x00000000000D6FFc74A8feb35aF5827bf57f6786` on all other networks

For your purposes, you can use the following methods:
```
function getRatesAndWeightsToEthWithCustomConnectors(IERC20 srcToken, bool useSrcWrappers, IERC20[] memory customConnectors, uint256 thresholdFilter) public view returns (uint256 wrappedPrice, OraclePrices.Data memory ratesAndWeights)
```
```
function getRatesAndWeightsWithCustomConnectors(IERC20 srcToken, IERC20 dstToken, bool useWrappers, IERC20[] memory customConnectors, uint256 thresholdFilter) public view returns (uint256 wrappedPrice, OraclePrices.Data memory ratesAndWeights)
```

!!! WARNING: **Do not use** these methods **on-chain** !!!

The returned values in these methods are `wrappedPrice` (if a wrapper exists) and a `Data` object from the `OraclePrices` library. For understanding the `Data` object, please refer to the NatSpec documentation in the source code [here](https://github.com/1inch/spot-price-aggregator/blob/deploy/offchain-oracle/contracts/libraries/OraclePrices.sol#L37-L41).

If the `wrappedPrice` is not 0, it means that there is a wrapper with a rate that does not depend on liquidity volume, so the list of rates from oracles in `Data` object doesn't matter and can be non-full.

If your program returns an `Out of gas` error, feel free to increase the gas for the transaction by adjusting the `gasLimit` property.

Good luck, and don't hesitate to reach out if you need further clarification.
