### ISSUE TITLE
Bad rate on rETH (base)

### ISSUE THREAD

**Issue by blakearnold** [1inch/spot-price-aggregator#186]
rETH on Base is almost double the real rate
asset address: 0xb6fe221fe9eef5aba221c348ba20a1bf5e73624c
2.16544 vs real 1.1161
<img width="339" alt="Screenshot 2024-09-16 at 3 21 37 PM" src="https://github.com/user-attachments/assets/212c6711-e273-4734-bf9c-afed390fa0b9">
<img width="988" alt="Screenshot 2024-09-16 at 3 24 24 PM" src="https://github.com/user-attachments/assets/110f40f8-581e-481f-8f1b-ecbb1dba7977">

**Comment by zZoMROT** [comment]
Thank you for pointing this out. 
The calculations for stable pools in the SolidlyLike oracles have been fixed, and the price is now being calculated correctly.

<img width="652" alt="Снимок экрана 2024-09-19 в 15 01 11" src="https://github.com/user-attachments/assets/17e22015-2072-48aa-8c7c-afa0df6e7949">
