### ISSUE TITLE
Multicall contract for AVAX

### ISSUE THREAD

**Issue by bgbahoue** [1inch/spot-price-aggregator#42]
Hello,

is there a multi call contract deployed on AVAX?

Something like [the multicall contract for ETH](https://etherscan.io/address/0xda3c19c6fe954576707fa24695efb830d9cca1ca) that you are using in your https://github.com/1inch/spot-price-aggregator/blob/master/examples/multiple-prices.js example?

**Comment by ZumZoom** [comment]
Hi!
Yes, there is one https://snowtrace.io/address/0xC4A8B7e29E3C8ec560cd4945c1cF3461a85a148d
